{% set version = "3.4.1" %}

package:
  name: nfft
  version: {{ version }}

source:
  fn: nfft-{{ version }}.tar.gz
  url: https://github.com/NFFT/nfft/releases/download/{{ version }}/nfft-{{ version }}.tar.gz
  md5: 9c2ad6cf86fe4a7bc0de8d2d92b101f4

build:
  number: 1
  skip: True  # [win]

requirements:
  build:
    - libtool
    - autoconf
    - automake
    - {{ compiler('c') }}
  host:
    - fftw
    - cunit
    - ncurses
  run:
    - fftw

test:
  commands:
    - test -f ${PREFIX}/lib/libnfft3.a
    - test -f ${PREFIX}/lib/libnfft3.so  # [linux]
    - test -f ${PREFIX}/lib/libnfft3.dylib  # [osx]
    - test -f ${PREFIX}/lib/libnfft3_threads.a
    - test -f ${PREFIX}/lib/libnfft3_threads.so  # [linux]
    - test -f ${PREFIX}/lib/libnfft3_threads.dylib  # [osx]

about:
  home: http://www.nfft.org/
  license: GPLv2
  summary: Non-equispaced fast Fourier transform (NFFT) library

extra:
    recipe-maintainers:
      - ghisvail
      - grlee77
