{% set version = "3.5.1" %}

package:
  name: nfft
  version: {{ version }}

source:
  fn: nfft-{{ version }}.tar.gz
  url: https://github.com/NFFT/nfft/releases/download/{{ version }}/nfft-{{ version }}.tar.gz
  sha256: bb95b2c240c6d972d4bb20740751a8efeba8b48b3be1d61fd59883909776fee3

build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - libtool
    - autoconf
    - automake
  host:
{% if not compiler('c').startswith("toolchain") %}
    - llvm-openmp  # [osx]
{% else %}
    - openmp 4.0.*  # [osx]
{% endif %}
    - fftw
    - cunit
    - ncurses
  run:
{% if not compiler('c').startswith("toolchain") %}
    - llvm-openmp  # [osx]
{% else %}
    - openmp 4.0.*  # [osx]
{% endif %}
    - fftw

test:
  commands:
    - test -f ${PREFIX}/lib/libnfft3.a
    - test -f ${PREFIX}/lib/libnfft3f.a
    - test -f ${PREFIX}/lib/libnfft3l.a
    - test -f ${PREFIX}/lib/libnfft3.so  # [linux]
    - test -f ${PREFIX}/lib/libnfft3f.so  # [linux]
    - test -f ${PREFIX}/lib/libnfft3l.so  # [linux]
    - test -f ${PREFIX}/lib/libnfft3.dylib  # [osx]
    - test -f ${PREFIX}/lib/libnfft3f.dylib  # [osx]
    - test -f ${PREFIX}/lib/libnfft3l.dylib  # [osx]
    - test -f ${PREFIX}/lib/libnfft3_threads.a
    - test -f ${PREFIX}/lib/libnfft3f_threads.a
    - test -f ${PREFIX}/lib/libnfft3l_threads.a
    - test -f ${PREFIX}/lib/libnfft3_threads.so  # [linux]
    - test -f ${PREFIX}/lib/libnfft3f_threads.so  # [linux]
    - test -f ${PREFIX}/lib/libnfft3l_threads.so  # [linux]
    - test -f ${PREFIX}/lib/libnfft3_threads.dylib  # [osx]
    - test -f ${PREFIX}/lib/libnfft3f_threads.dylib  # [osx]
    - test -f ${PREFIX}/lib/libnfft3l_threads.dylib  # [osx]

about:
  home: http://www.nfft.org/
  license: GPLv2
  summary: Non-equispaced fast Fourier transform (NFFT) library

extra:
  recipe-maintainers:
    - ghisvail
    - grlee77
    - kohr-h
