{% set version = "3.4.0" %}

package:
  name: nfft
  version: {{ version }}

source:
  fn: nfft-{{ version }}.tar.gz
  url: https://github.com/NFFT/nfft/releases/download/{{ version }}/nfft-{{ version }}.tar.gz
  md5: f2e0f7848fe84347ad8a4f01dc9ce297

build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - fftw
    - gcc
    - libtool
    - autoconf
    - automake
    - cunit
    - ncurses 5.9*
  run:
    - fftw
    - libgcc

test:
  commands:
    - test -f ${PREFIX}/lib/libnfft3.a
    - test -f ${PREFIX}/lib/libnfft3.so  # [linux]
    - test -f ${PREFIX}/lib/libnfft3.dylib  # [osx]
    - test -f ${PREFIX}/lib/libnfft3_threads.a
    - test -f ${PREFIX}/lib/libnfft3_threads.so  # [linux]
    - test -f ${PREFIX}/lib/libnfft3_threads.dylib  # [osx]

about:
  home: http://www.nfft.org/
  license: GPLv2
  summary: Non-equispaced fast Fourier transform (NFFT) library

extra:
    recipe-maintainers:
      - ghisvail
      - grlee77
